[profile.default]
src = 'src'
out = '.cache/out'
libs = ['lib']
cache_path = '.cache/cache'
broadcast = '.cache/broadcast'
fs_permissions = [{ access = 'read-write', path = '/'}]

remappings = [
    "@openzeppelin=lib/openzeppelin-contracts",
    "@uniswap/v3-core=lib/uniswap/v3-core",
    "@uniswap/v3-periphery=lib/uniswap/v3-periphery",
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config